import type { FinanceMovement, PaymentMethod } from "./types";

export const TODAY = "2026-07-21";

export const PAYMENT_METHODS: PaymentMethod[] = [
  "PIX",
  "Dinheiro",
  "Cartão de Crédito",
  "Cartão de Débito",
  "Transferência",
];

export const TEAM = [
  "Ana Paula",
  "Carla Mendes",
  "Fernanda Lima",
  "Juliana Costa",
  "Roberto Alves",
];

export const initialMovements: FinanceMovement[] = [
  {
    id: "m1",
    type: "entrada",
    personName: "Maria Silva",
    description: "Consulta de rotina",
    paymentMethod: "PIX",
    responsible: "Ana Paula",
    amount: 280,
    date: "2026-07-21",
    time: "09:15",
  },
  {
    id: "m2",
    type: "entrada",
    personName: "João Pedro Santos",
    description: "Limpeza dental",
    paymentMethod: "Cartão de Débito",
    responsible: "Carla Mendes",
    amount: 350,
    date: "2026-07-21",
    time: "10:00",
  },
  {
    id: "m3",
    type: "saida",
    personName: "Dental Supply LTDA",
    description: "Compra de materiais descartáveis",
    paymentMethod: "PIX",
    responsible: "Fernanda Lima",
    amount: 420,
    date: "2026-07-21",
    time: "10:40",
    notes: "Nota fiscal 4521",
  },
  {
    id: "m4",
    type: "entrada",
    personName: "Ana Beatriz Rocha",
    description: "Restauração",
    paymentMethod: "Cartão de Crédito",
    responsible: "Ana Paula",
    amount: 680,
    date: "2026-07-21",
    time: "11:30",
  },
  {
    id: "m5",
    type: "entrada",
    personName: "Carlos Eduardo",
    description: "Avaliação ortodôntica",
    paymentMethod: "Dinheiro",
    responsible: "Juliana Costa",
    amount: 150,
    date: "2026-07-21",
    time: "14:10",
  },
  {
    id: "m6",
    type: "saida",
    personName: "Funcionários",
    description: "Adiantamento de vale-transporte",
    paymentMethod: "Dinheiro",
    responsible: "Roberto Alves",
    amount: 180,
    date: "2026-07-21",
    time: "15:00",
  },
  {
    id: "m7",
    type: "entrada",
    personName: "Patricia Oliveira",
    description: "Clareamento dental",
    paymentMethod: "PIX",
    responsible: "Carla Mendes",
    amount: 900,
    date: "2026-07-21",
    time: "16:20",
  },
  {
    id: "m8",
    type: "entrada",
    personName: "Lucas Fernandes",
    description: "Extração simples",
    paymentMethod: "Transferência",
    responsible: "Ana Paula",
    amount: 450,
    date: "2026-07-20",
    time: "09:45",
  },
  {
    id: "m9",
    type: "saida",
    personName: "Concessionária de Energia",
    description: "Conta de energia elétrica",
    paymentMethod: "Transferência",
    responsible: "Fernanda Lima",
    amount: 620,
    date: "2026-07-20",
    time: "11:00",
  },
  {
    id: "m10",
    type: "entrada",
    personName: "Beatriz Almeida",
    description: "Consulta + radiografia",
    paymentMethod: "Cartão de Crédito",
    responsible: "Juliana Costa",
    amount: 320,
    date: "2026-07-20",
    time: "15:30",
  },
  {
    id: "m11",
    type: "entrada",
    personName: "Rafael Souza",
    description: "Manutenção de aparelho",
    paymentMethod: "PIX",
    responsible: "Carla Mendes",
    amount: 200,
    date: "2026-07-19",
    time: "10:20",
  },
  {
    id: "m12",
    type: "saida",
    personName: "Lab Prótese Oral",
    description: "Pagamento laboratório de prótese",
    paymentMethod: "PIX",
    responsible: "Roberto Alves",
    amount: 850,
    date: "2026-07-19",
    time: "14:00",
  },
  {
    id: "m13",
    type: "entrada",
    personName: "Camila Torres",
    description: "Implante — parcela 2/4",
    paymentMethod: "Cartão de Débito",
    responsible: "Ana Paula",
    amount: 1200,
    date: "2026-07-18",
    time: "11:15",
  },
  {
    id: "m14",
    type: "saida",
    personName: "Limpeza Clínica",
    description: "Serviço de limpeza mensal",
    paymentMethod: "Transferência",
    responsible: "Fernanda Lima",
    amount: 380,
    date: "2026-07-15",
    time: "08:30",
  },
  {
    id: "m15",
    type: "entrada",
    personName: "Diego Martins",
    description: "Canal — sessão 1",
    paymentMethod: "Dinheiro",
    responsible: "Juliana Costa",
    amount: 550,
    date: "2026-07-15",
    time: "16:45",
  },
];
